name: Deploy showcase

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
              ${{ runner.os }}-node-
      - run: yarn install
      - run: yarn nx build showcase
      - run: ssh-keyscan -H ${{ secrets.SSH_REMOTE_HOST }} >> ~/.ssh/known_hosts
      - uses: easingthemes/ssh-deploy@main
        with:
          SCRIPT_BEFORE: ls
          ARGS: "-rlgoDzvc -i"
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SOURCE: "dist/showcase/"
          REMOTE_HOST: ${{ secrets.SSH_REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.SSH_REMOTE_USER }}
          TARGET: "/var/www/ngwr-showcase/"
