name: Release

on:
  workflow_dispatch:
    inputs:
      mode:
        type: choice
        description: release type
        required: true
        default: 'minor'
        options:
          - patch
          - minor
          - major

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup git config
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
            git config --global user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"
            git config --global user.name "$(gh api /users/${GITHUB_ACTOR} | jq .name -r)"
            git config -l
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: yarn install
      - name: Run release
        run: yarn release:${{ github.event.inputs.mode }} --ci-mode
